# Generated by Django 2.2.3 on 2019-08-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190730_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follower',
            field=models.ManyToManyField(blank=True, related_name='_profile_follower_+', to='app.Profile'),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
