# Generated by Django 2.2.3 on 2019-08-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190806_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follower',
            field=models.ManyToManyField(blank=True, null=True, related_name='_profile_follower_+', to='app.Profile'),
        ),
    ]
